- app/controllers/conditions_controller.rb
- app/models/condition.rb
- app/views/conditions/index.html.erb
- app/views/conditions/show.html.erb
- config/routes.rb
- db/migrate/20180721200019_create_conditions.rb
- db/schema.rb
- spec/features/user_sees_conditions_show_spec.rb
- spec/features/user_visit_conditions_index_spec.rb
- spec/models/condition_spec.rb
_x_ Wrote Tests
_x_ Implemented
____ Reviewed
- [] Bug Fix
Conditions index and show, with tests
conditions index and show
Link:
> Condition show

- app/controllers/stations_controller.rb
- app/models/station.rb
- app/views/stations/index.html.erb
- app/views/stations/show.html.erb
- config/routes.rb
- db/migrate/20180721195000_create_stations.rb
- db/schema.rb
- spec/features/station_show_spec.rb
- spec/features/visitor_station_index_spec.rb
- spec/models/station_spec.rb
_x_ Wrote Tests
_x_ Implemented
____ Reviewed
- [] Bug Fix
Stations Index and Show Pages, user story 1 and 2.
Stations Index and Show Pages, user story 1 and 2. Slug routes for station show pages.
Link:
> Stations show

- app/controllers/orders_controller.rb
- app/models/accessory.rb
- app/models/order.rb
- app/models/order_accessory.rb
- app/models/user.rb
- app/views/dashboard/index.html.erb
- app/views/orders/show.html.erb
- config/routes.rb
- db/migrate/20180724000240_create_orders.rb
- db/migrate/20180724000549_create_order_accessories.rb
- db/schema.rb
- spec/features/orders/user_visits_order_show_page_spec.rb
- spec/models/accessory_spec.rb
- spec/models/order_accessories_spec.rb
- spec/models/order_accessory_spec.rb
- spec/models/order_spec.rb
____ Reviewed
- [] Bug Fix
Link:
> Order table

- app/controllers/trips_controller.rb
- app/models/trip.rb
- app/views/trips/dashboard.html.erb
- config/routes.rb
- spec/features/trips/dashboard_spec.rb
- spec/models/accessory_spec.rb
- spec/models/trip_spec.rb
__x__ Wrote Tests
__x__ Implemented
__x__ Reviewed
with skips.
- [] The code will run locally on puma - unchecked.
- [] Bug Fix
Adds methods and view for Trips Dashboard.
Methods and view for Trips Dashboard.
Link:
> Trips class methods and dashboard tests

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/models/station.rb
- app/models/trip.rb
- app/models/user.rb
- app/views/dashboard/index.html.erb
- app/views/sessions/new.html.erb
- app/views/trips/index.html.erb
- app/views/trips/show.html.erb
- config/routes.rb
- db/migrate/20180721195000_create_stations.rb
- db/migrate/20180722215842_create_trips.rb
- db/migrate/20180723232406_add_role_to_users.rb
- db/schema.rb
- db/seeds.rb
- spec/features/stations/station_show_spec.rb
- spec/features/stations/visitor_station_index_spec.rb
- spec/features/trips/dashboard_spec.rb
- spec/features/trips/visitor_can_see_trip_index_spec.rb
- spec/features/trips/visitor_can_visit_trip_show_spec.rb
- spec/features/users/user_auth_spec.rb
- spec/models/accessory_spec.rb
- spec/models/station_spec.rb
- spec/models/trip_spec.rb
- spec/models/user_spec.rb
_x_ Wrote Tests
_x_ Implemented
_x_ Reviewed
- [] Bug Fix
Adds user authentication, authorization, db relationship between stations and trips.
A ton of code.
Only what it broke
Link: 
https://media.giphy.com/media/lNubxCPAPvSUw/giphy.gif
> Auth station trips

- app/controllers/stations_controller.rb
- app/models/station.rb
- app/views/stations/dashboard.html.erb
- config/routes.rb
- spec/features/stations/user_sees_station_dashboard_spec.rb
- spec/features/trips/dashboard_spec.rb
- spec/models/station_spec.rb
- spec/models/trip_spec.rb
__x__ Implemented
____ Reviewed
- [] Bug Fix
Stations class methods and features for dashboard page
Several class methods in model, a dashboard path, a controller action and a view page.
the model tests for oldest and youngest station were flip flopped, I changed that.
Link:
> Stations models and functionality

- app/controllers/carts_controller.rb
- app/views/carts/index.html.erb
- config/routes.rb
- spec/features/cart/visitor_sees_cart_show_page_spec.rb
____ Reviewed
- [] Bug Fix
Link:
> Remove from cart

- app/controllers/admin/base_controller.rb
- app/controllers/admin/dashboard_controller.rb
- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/views/admin/dashboard/index.html.erb
- config/routes.rb
- spec/features/admins/admin_can_login_spec.rb
- spec/features/cart/cart_features_spec.rb
- spec/features/cart/visitor_sees_cart_show_page_spec.rb
____ Reviewed
- [] Bug Fix
Link:
> Admin login

- app/controllers/stations_controller.rb
- app/models/station.rb
- app/views/stations/index.html.erb
- db/migrate/20180725234754_add_slug_to_stations.rb
- db/schema.rb
- spec/features/stations/station_show_spec.rb
____ Reviewed
- [] Bug Fix
Link:
> Fix slug retry

- app/controllers/orders_controller.rb
- app/views/carts/index.html.erb
- config/routes.rb
- spec/features/cart/user_can_checkout_spec.rb
____ Reviewed
- [] Bug Fix
Link:
> Cart checkout

- app/controllers/orders_controller.rb
- app/controllers/sessions_controller.rb
- app/views/accessories/index.html.erb
____ Reviewed
- [] Bug Fix
Link:
> Add clear cart for order and logout

- db/seeds.rb
____ Reviewed
- [] Bug Fix
Link:
> filters seed files for deployment

- app/models/station.rb
- app/views/stations/show.html.erb
- spec/features/stations/admin_station_crud_spec.rb
- spec/models/station_spec.rb
____ Reviewed
- [] Bug Fix
Link:
> Refactors two trip methods to continue to pass tests

- app/controllers/carts_controller.rb
- app/views/layouts/application.html.erb
- spec/features/cart/cart_features_spec.rb
____ Reviewed
- [] Bug Fix
Link:
> adds logic to cart controller to ignore negative quantities on update

- app/controllers/admin/bikeshops_controller.rb
- app/models/accessory.rb
- app/views/admin/bikeshops/edit.html.erb
- app/views/admin/bikeshops/index.html.erb
- app/views/admin/bikeshops/new.html.erb
- app/views/admin/dashboard/index.html.erb
- config/routes.rb
- db/migrate/20180722173443_create_accessories.rb
- db/schema.rb
- spec/features/admins/admin_accessories_spec.rb
- spec/models/accessory_spec.rb
____ Reviewed
- [] Bug Fix
Link:
> Clever branch name

- app/models/order.rb
- app/views/carts/index.html.erb
- app/views/dashboard/index.html.erb
- db/seeds.rb
- spec/features/cart/user_can_checkout_spec.rb
- spec/features/stations/admin_station_crud_spec.rb
- spec/features/users/user_auth_spec.rb
- spec/models/accessory_spec.rb
____ Reviewed
- [] Bug Fix
Link:
> Todo branch

- app/views/conditions/index.html.erb
- app/views/trips/index.html.erb
- spec/features/conditions/user_visit_conditions_index_spec.rb
- spec/features/trips/visitor_can_see_trip_index_spec.rb
____ Reviewed
- [] Bug Fix
Link:
> adds links to show pages from trips and consitions dashboard

- app/controllers/carts_controller.rb
- app/views/layouts/application.html.erb
- spec/features/cart/visitor_sees_cart_show_page_spec.rb
____ Reviewed
- [] Bug Fix
Link:
> Adds links to the accessory page from the remove from cart flash message

- app/views/carts/index.html.erb
- app/views/conditions/index.html.erb
- app/views/welcome/index.html.erb
____ Reviewed
- [] Bug Fix
Link:
> Notes branch

- README.md
- app/models/trip.rb
- spec/features/conditions/conditions_dashboard_spec.rb
____ Reviewed
- [] Bug Fix
Link:
> Fix conditions dashboard
